<?php

/**
 * SqlServerHelper - Classe utilitária para operações com SQL Server
 *
 * Funções disponíveis:
 * - ConectParams: Estabelece conexão com o banco de dados
 * - ExecuteNonQuery: Executa comandos sem retorno de dados (INSERT, UPDATE, DELETE)
 * - GetOne: Retorna um único registro
 * - GetMany: Retorna múltiplos registros
 * - Prepare: Prepara uma query com parâmetros
 *
 * @author Generated by Claude
 * @version 1.0
 */

require 'conexao.php';

class SqlServerHelper
{
    private $connection = null;
    private $host;
    private $database;
    private $port;

    /**
     * Construtor da classe
     *
     * @param string $host Endereço do servidor
     * @param string $database Nome do banco de dados
     * @param int $port Porta (padrão: 1433)
     */
    public function __construct($host = '', $database = '', $port = 1433)
    {
        $this->host = $host;
        $this->database = $database;
        $this->port = $port;
    }

    /**
     * ConectParams - Estabelece conexão com o SQL Server
     *
     * @param array $params Array associativo com parâmetros de conexão
     *                      ['host', 'database', 'username', 'password', 'port']
     * @return PDO|false Retorna objeto PDO ou false em caso de erro
     *
     * @example
     * $params = [
     *     'host' => 'localhost',
     *     'database' => 'meudb',
     *     'username' => 'sa',
     *     'password' => 'senha123',
     *     'port' => 1433
     * ];
     * $db->ConectParams($params);
     */
    public function ConectParams($params = [])
    {
        try {
            // Atualiza os parâmetros se fornecidos
            if (!empty($params)) {
                $this->host = $params['host'] ?? $this->host;
                $this->database = $params['database'] ?? $this->database;

                $this->port = $params['port'] ?? $this->port;
            }

            // String de conexão para SQL Server
            $dsn = "sqlsrv:Server={$this->host},{$this->port};Database={$this->database}";

            // Opções de conexão
            $options = [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ];

            $this->connection = new PDO($dsn, options: $options);

            return $this->connection;
        } catch (PDOException $e) {
            error_log("Erro de conexão SQL Server: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Retorna a conexão ativa
     *
     * @return PDO|null
     */
    public function getConnection()
    {
        return $this->connection;
    }

    /**
     * ExecuteNonQuery - Executa comandos que não retornam dados (INSERT, UPDATE, DELETE)
     *
     * @param string $query Query SQL a ser executada
     * @param array $params Parâmetros para prepared statement
     * @return int|false Número de linhas afetadas ou false em caso de erro
     *
     * @example
     * $sql = "INSERT INTO usuarios (nome, email) VALUES (:nome, :email)";
     * $params = ['nome' => 'João', 'email' => 'joao@email.com'];
     * $rowsAffected = $db->ExecuteNonQuery($sql, $params);
     */
    public function ExecuteNonQuery($query, $params = [])
    {
        try {
            if ($this->connection === null) {
                throw new Exception("Conexão não estabelecida. Use ConectParams() primeiro.");
            }

            $stmt = $this->connection->prepare($query);
            $stmt->execute($params);

            return $stmt->rowCount();
        } catch (PDOException $e) {
            error_log("Erro ao executar ExecuteNonQuery: " . $e->getMessage());
            return false;
        }
    }

    /**
     * GetOne - Retorna um único registro do banco de dados
     *
     * @param string $query Query SQL a ser executada
     * @param array $params Parâmetros para prepared statement
     * @return array|false Array associativo com o registro ou false se não encontrado
     *
     * @example
     * $sql = "SELECT * FROM usuarios WHERE id = :id";
     * $params = ['id' => 1];
     * $usuario = $db->GetOne($sql, $params);
     */
    public function GetOne($query, $params = [])
    {
        try {
            if ($this->connection === null) {
                throw new Exception("Conexão não estabelecida. Use ConectParams() primeiro.");
            }

            $stmt = $this->connection->prepare($query);
            $stmt->execute($params);

            $result = $stmt->fetch(PDO::FETCH_ASSOC);

            return $result !== false ? $result : false;
        } catch (PDOException $e) {
            error_log("Erro ao executar GetOne: " . $e->getMessage());
            return false;
        }
    }

    /**
     * GetMany - Retorna múltiplos registros do banco de dados
     *
     * @param string $query Query SQL a ser executada
     * @param array $params Parâmetros para prepared statement
     * @return array|false Array de arrays associativos ou false em caso de erro
     *
     * @example
     * $sql = "SELECT * FROM usuarios WHERE ativo = :ativo";
     * $params = ['ativo' => 1];
     * $usuarios = $db->GetMany($sql, $params);
     */
    //public function GetMany($query, $params = [])
    public function GetMany(string $query, $params = null)
    {
        try {
            if ($this->connection === null) {
                throw new Exception("Conexão não estabelecida. Use ConectParams() primeiro.");
            }

            $stmt = $this->connection->prepare($query);
            $stmt->execute($params);

            $results = $stmt->fetchAll(PDO::FETCH_ASSOC);

            return $results;
        } catch (PDOException $e) {
            error_log("Erro ao executar GetMany: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Prepare - Prepara uma query SQL para execução posterior
     *
     * @param string $query Query SQL a ser preparada
     * @return PDOStatement|false PDOStatement preparado ou false em caso de erro
     *
     * @example
     * $sql = "INSERT INTO logs (mensagem, data) VALUES (:msg, :data)";
     * $stmt = $db->Prepare($sql);
     * if ($stmt) {
     *     $stmt->execute(['msg' => 'Log 1', 'data' => date('Y-m-d')]);
     *     $stmt->execute(['msg' => 'Log 2', 'data' => date('Y-m-d')]);
     * }
     */
    public function Prepare($query)
    {
        try {
            if ($this->connection === null) {
                throw new Exception("Conexão não estabelecida. Use ConectParams() primeiro.");
            }

            return $this->connection->prepare($query);
        } catch (PDOException $e) {
            error_log("Erro ao preparar query: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Inicia uma transação
     *
     * @return bool
     */
    public function beginTransaction()
    {
        if ($this->connection !== null) {
            return $this->connection->beginTransaction();
        }
        return false;
    }

    /**
     * Confirma uma transação
     *
     * @return bool
     */
    public function commit()
    {
        if ($this->connection !== null) {
            return $this->connection->commit();
        }
        return false;
    }

    /**
     * Reverte uma transação
     *
     * @return bool
     */
    public function rollback()
    {
        if ($this->connection !== null) {
            return $this->connection->rollBack();
        }
        return false;
    }

    /**
     * Retorna o último ID inserido
     *
     * @return string|false
     */
    public function lastInsertId()
    {
        if ($this->connection !== null) {
            return $this->connection->lastInsertId();
        }
        return false;
    }

    /**
     * Fecha a conexão com o banco de dados
     */
    public function close()
    {
        $this->connection = null;
    }

    /**
     * Destrutor - fecha a conexão automaticamente
     */
    public function __destruct()
    {
        $this->close();
    }
}