<?php

/**
 * SqlServerHelper - Classe utilitária para operações com SQL Server
 *
 * Funções disponíveis:
 * - ConectParams: Estabelece conexão com o banco de dados
 * - ExecuteNonQuery: Executa comandos sem retorno de dados (INSERT, UPDATE, DELETE)
 * - GetOne: Retorna um único registro
 * - GetMany: Retorna múltiplos registros
 * - Prepare: Prepara uma query com parâmetros
 *
 * @author Generated by Claude
 * @version 1.0
 */

require 'conexao.php';

class DataBase
{
    private $connection = '';
    private $host = 'ALESSANDRAL\LOCALHOST';
    private $database = 'Biblioteca';


    public function __construct(){
        try {
            $this->connection = new PDO(
                "sqlsrv:Server={$this->host};Database={$this->database}",   

            );
            $this->connection->setAttribute(PDO:: ATTR_ERRMODE, PDO:: ERRMODE_EXCEPTION);

        } catch (PDOException $e){

            throw new Exception ("Erro de conexao:" . $e->getMessage());

        }
    }    


    public function getConnection()
    {
        return $this->connection;
    }

    public function ExecuteNonQuery($query, $params = [])
    {

        try{
            $stmt = $this->connection->prepare($query);
            $stmt->execute($params);
            $result = $stmt-> rowCount();

        } catch (PDOException $e){
         
            throw new Exception("Erro ao executar a query:" . $e->getMessage());

        }
    }

    public function GetOne($query, $params = [])
    {
        try {
            $stmt = $this->connection->prepare($query);
            $stmt->execute($params);
            $result = $stmt->fetch(PDO::FETCH_ASSOC);
            return $result !== false ? $result : false;


        } catch (PDOException $e) {

             throw new Exception("Erro ao executar a query:" . $e->getMessage());
             return false;
        }
    }

public function GetMany($query, $params = []) {
        try {
            $stmt = $this->connection->prepare($query);
            $stmt->execute($params);

            $results = $stmt->fetchAll(PDO::FETCH_ASSOC);
            return $results;

        } catch (PDOException $e) {
             throw new Exception("Erro ao executar o GetMany:" . $e->getMessage());
            return [];
        }
    }

    public function beginTransaction()
    {
        if ($this->connection !== null) {
            return $this->connection->beginTransaction();
        }
        return false;
    }


    public function commit()
    {
        if ($this->connection !== null) {
            return $this->connection->commit();
        }
        return false;
    }


    public function rollback()
    {
        if ($this->connection !== null) {
            return $this->connection->rollBack();
        }
        return false;
    }

    public function lastInsertId()
    {
        if ($this->connection !== null) {
            return $this->connection->lastInsertId();
        }
        return false;
    }

    public function close()
    {
        $this->connection = null;
    }


    public function __destruct()
    {
        $this->close();
    }
}